function loadHomePage() {
    document.getElementById('content').innerHTML = `
        <h1>Welcome to Quick Attend</h1>
        <p>Click on the buttons in the navbar to navigate.</p>

        <!-- Description Div -->
        <div class="mt-4">
            <h2>About Us</h2>
            <p>A QR (Quick Response) code scanner for attendance purposes. In this project, the user and admin panel allows the admin to add student details, generate QR codes, and generate attendance reports for each student.</p>
            <p>On the other hand, users can mark their attendance using the QR codes generated by the admin panel. Additionally, users (students) can check their attendance history.</p>
        </div>

        <!-- Features Div -->
        <div class="mt-4">
            <h2>Features</h2>
            <div class="row">
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">QR Code Generation</h5>
                            <ul>
                                <li>Unique QR codes for each event or session.</li>
                                <li>Personal QR codes for students or employees.</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Attendance Marking</h5>
                            <ul>
                                <li>Scan QR codes to mark attendance.</li>
                                <li>Real-time attendance status update.</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">User Authentication</h5>
                            <ul>
                                <li>Integration with student or employee ID systems.</li>
                                <li>Secure login for administrators and users.</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Mobile App Integration</h5>
                            <ul>
                                <li>QR code scanning via mobile devices.</li>
                                <li>Cross-platform compatibility (iOS, Android).</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Web Portal</h5>
                            <ul>
                                <li>Web interface for managing and viewing attendance records.</li>
                                <li>Administrative controls for creating and managing events.</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Reporting and Analytics</h5>
                            <ul>
                                <li>Detailed attendance reports.</li>
                                <li>Analytics on attendance trends and patterns.</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 mb-4">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Defaulter List Generator</h5>
                            <ul>
                                <li>Generates a defaulter list at the end of every month.</li>
                                <li>List goes directly to the admin.</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    `;
}

function loadAdminPage() {
    document.getElementById('content').innerHTML = `
        <h1>Hello World - Admin Page</h1>
    `;
}

function loadStudentPage() {
    document.getElementById('content').innerHTML = `
        <h1>Hello World - Student Page</h1>
    `;
}
